name: Continuous integration example

on: 
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['8','9','11', '17', '19']
    steps:
       uses: actions/checkout@v3
       name: Set up ${{matrix.java}}
       uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}
       run: mvn test
