name: Por cada commit en Release-* ejecución de varias pruebas
on:
  push:
    branches:
      - 'release/**'
env:
  GITHUB_REF: ${{ github.ref }}
  BRANCH_NAME: ${{ github.ref.replace('refs/heads/', '') }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
          fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Ejecución de ReviewServiceUnitaryTest por commit en ${{env.GITHUB_REF}}
        run: echo "hola soy ReviewServiceUnitaryTest"
      - name: Ejecución de OpenLibraryServiceIntegrationTest por commit en ${{env.GITHUB_REF}}
        run: echo "hola soy OpenLibraryServiceIntegrationTest"